### ISSUE TITLE
Protolize is not working with EEGlab 13

### ISSUE THREAD

**Issue by ishiikurisu** [ishiikurisu/P2#10]
The newer versions of EEGLab raise some errors when using the EEG module on Protolize!, specially when it comes to running ICA and locating channels (the application performs the mapping but the locations do not appear). Why is it so?

**Comment by ishiikurisu** [comment]
Protolize can run ICA on individual EEG sets; but apparently it has some trouble dealing with many sets at the same time. I still have to test the channel locations.

**Comment by crs94** [comment]
EEGLab 13 messes up the channel location when one tries to save a new CED file, so this version of EEGLab can't be used to create new localization files. As for the trouble running multiple sets it can be solved by turning on one of the memory managing options (though I do not recommend it because it'll have to be turned off again if one wishes to run the ICA again).

A modified version of EEGLab 10 (one in which the files responsible for importing data are replaced for the ones in EEGLab 13) is better suited to run all the modules and reduce the problems.
